version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: rqg-translation-api:1.0
    container_name: rqg-translation-api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
    volumes:
      - ./models/saved_model:/app/models/saved_model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 